### ISSUE TITLE
Unknown content size causes problem for resize script

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2848] opened 2024-12-09 15:01 UTC
*Problem description*

**Comment by emmachughes** [comment] 2024-12-10 08:40
Example URL: https://ndla.no/r/matematikk-1p-y---ba/prosent-og-prosentfaktor-promille/25b89159dd#Oppgave-19

When opening in a browser with smooth scrolling enabled, you are not taken to the correct location on the page.

The problem is caused by `scrollIntoView()`/`scrollTo()` (or similar) being invoked with the "smooth" behaviour. This causes a race condition, as the resizing is still figuring itself out after scrolling has begun, but before it's reached its destination. The correct behaviour can be observed if loading the page in Firefox with smooth scrolling disabled in the settings.

This will have to be fixed on the side consuming Edlib by explicitly invoking the "immediate" scrolling behaviour. H5Ps do not (as far as we can tell) have a height that is known in advance, so fixing this on Edlib's side is not feasible.

**Closed** 2024-12-11 08:15 UTC
Labels: NDLA
