### ISSUE TITLE
Keep filters when toggling between Shared content and my content

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#746] opened 2022-03-02 12:26 UTC
**Keep filters**
When jumping between Shared content and my content, keeping the filter is a nice to have.

**Comment by tmkarlsen** [comment] 2022-09-07 19:03
@emmachughes whilst looking at the left menu behavior.

**Comment by chrieinv** [comment] 2022-09-12 13:02
Duplicate of #1623?

**Closed** 2023-04-26 07:08 UTC
Labels: enhancement, needs triage
